const activites = [
  "Agriculture, Sylviculture Et Pêche",
  "Industries Extractives",
  "Industrie Manufacturière",
  "Production Et Distribution D'électricité, De Gaz, De Vapeur Et D'air Conditionné",
  "Production Et Distribution D'eau ; Assainissement, Gestion Des Déchets Et Dépollution ",
  "Construction",
  "Commerce ; Réparation D'automobiles Et De Motocycles",
  "Transports Et Entreposage",
  "Hébergement Et Restauration",
  "Information Et Communication",
  "Activités Financières Et D'assurance",
  "Activités Immobilières",
  "Activités Spécialisées, Scientifiques Et Techniques",
  "Activités De Services Administratifs Et De Soutien",
  "Administration Publique",
  "Enseignement",
  "Santé Humaine Et Action Sociale",
  "Arts, Spectacles Et Activités Récréatives",
  "Autres Activités De Services",
  "Activités Extra-Territoriales",
  "Activités Des Ménages En Tant Qu'employeurs ; Activités Indifférenciées Des Ménages En Tant Que Producteurs De Biens Et Services Pour Usage Propre",
];

export default activites;
