const categories = [
  "",
  "Produits chimiques",
  "Peintures et vernis",
  "Cosmétique et substance nettoyante",
  "Huiles et lubrifiants industriels",
  "Médicaments",
  "Métaux communs et alliage",
  "Machines-outils",
  "Outils manuels",
  "Appareils électriques et scientifiques",
  "Appareils médicaux",
  "Appareil de contrôle de l'environnement",
  "Véhicules",
  "Armes à feu",
  "Bijoux",
  "Instruments de musique",
  "Papeterie",
  "Articles en caoutchouc",
  "Maroquinerie",
  "Matériaux de construction",
  "Meubles",
  "Articles ménagers et verre",
  "Cordes et fibres",
  "Fils",
  "Tissu",
  "Vêtements et chaussures",
  "Fantaisie",
  "Tapis et revêtement de sol",
  "Jouets et articles de sport",
  "Viande et aliments transformés",
  "Aliment de Base",
  "Produits agricoles",
  "Boisson légère y compris la bière",
  "Boissons alcoolisées",
  "Produit du Tabac",
  "Publicité et services aux entreprises",
  "Assurances et services financiers",
  "Services de construction et de réparation de bâtiments",
  "Télécommunication",
  "Transport et services de stockage",
  "Services de traitement de matériaux",
  "Services d'éducation et de divertissement",
  "Informatique, scientifique et juridique",
  "Services de restauration",
  "Services médicaux et vétérinaires",
  "Services personnels et sociaux",
];

export default categories;
