const villes = [
  "Tanger-Assilah",
  "Tanger",
  "Assila",
  "Fnideq",
  "Tétouan",
  "Fahs-Anjra",
  "Larache",
  "Hoceïma",
  "Hoceima",
  "Chefchaouen",
  "Ouezzane",
  "Oujda",
  "Nador",
  "Driouch",
  "Jerada",
  "Berkane",
  "Taourirt",
  "Guercif",
  "Figuig",
  "Fès",
  "Meknès",
  "Hajeb",
  "Ifrane",
  "Moulay Yaâcoub",
  "Séfrou",
  "Boulemane",
  "Taounate",
  "Taza",
  "Rabat",
  "Salé",
  "Skhirate",
  "Temara",
  "Kénitra",
  "Khémisset",
  "Sidi Kacem",
  "Sidi Slimane",
  "Béni Mellal",
  "Azilal",
  "Fquih Ben Salah",
  "Khénifra",
  "Khouribga",
  "Mohammédia",
  "Jadida",
  "Nouaceur",
  "Médiouna",
  "Benslimane",
  "Berrechid",
  "Settat",
  "Sidi Bennour",
  "Marrakech",
  "Chichaoua",
  "Al Haouz",
  "Sraghna",
  "Essaouira",
  "Rehamna",
  "Safi",
  "Youssoufia",
  "Errachidia",
  "Ouarzazate",
  "Midelt",
  "Tinghir",
  "Zagora",
  "Agadir",
  "Aït Melloul",
  "Inezgane",
  "Chtouka-Aït Baha",
  "Taroudant",
  "Tiznit",
  "Tata",
  "Guelmim",
  "Assa-Zag",
  "Tan-Tan",
  "Sidi Ifni",
  "Laâyoune",
  "Boujdour",
  "Tarfaya",
  "Es-Semara",
  "Dahab",
  "Témara",
  "had soualem",
  "Aousserd",
  "Dakhla",
  "Skhirat",
  "Zenata",
  "Zear",
  "ZAG",
  "Zaer",
  "Tin Mansour",
  "Timoulilte",
  "Tiferuine",
  "Tifelt",
  "Tetouan",
  "Tamesna",
  "Tamesloht",
  "Souk EL ARBAA",
  "SMARA",
  "SIDI YAHYA DES ZEARS",
  "Sidi Rahal, Birjdid",
  "SIDI BOUKNADEL",
  "SIDI BOUATMANE",
  "Sidi Bibi",
  "Sidi allal el bahraoui",
  "Saidia",
  "SAADIA",
  "Rissani",
  "REBAT EL KHAIR",
  "Rabbat",
  "OURZAZAT",
  "Ouled Salah, Bouskoura",
  "Ouled nemma",
  "Oued Zem",
  "Oued Law",
  "Ouarazazate",
  "Oualidia",
  "Nouacer",
  "Msoun",
  "Mrirt",
  "Moulay bousselham",
  "MERZOUGA",
  "M'diq",
  "Massa",
  "martil",
  "MANSOURIA",
  "MACHRAA BELKSIRI",
  "Ksar el kebir",
  "Khemiss Zemamra",
  "KETAMA ESSAGHENE",
  "Kasba tadla",
  "Jorf Lasfar",
  "Inzegan",
  "INCHADEN",
  "HAOUZIA",
  "Gueznaia",
  "Fkih Ben Salah",
  "ESSOUIRA",
  "ER-RICH",
  "ERFOUD",
  "EL MENZAL",
  "El ksiba",
  "ELKLEA",
  "El jadidz",
  "DCHEIRA AL JIHADIA",
  "Dar Chaoui",
  "Dar Bouazza",
  "Chtouka Ait Baha",
  "Casablanca",
  "Bouznika",
  "Bouskoura",
  "BOUFEKRANE",
  "Boudnib",
  "Bouarfa",
  "BNIMELLAL",
  "Bir jdid",
  "Biougra",
  "BERRCHID",
  "BENI-MELLAL",
  "BENGURIR",
  "BENGUERIR",
  "Ben guerir",
  "Azrou",
  "Azemmour",
  "ASSA",
  "Aourir",
  "AOUAMRA",
  "AL HOUCEIMA",
  "Al aroui",
  "AIN SEBAA",
  "Ain Harrouda",
  "Ain dorij",
  "Ain beni mathar",
  "Ain ATIQ",
  "Ain Atiq",
  "Ain Aouda",
]

export default villes